[project]
name = "sdj-designers"
version = "0.1.0"
description = "Overview of Spiel des Jahres winning designers"
authors = [{ name = "Markus Shepherd", email = "markus@recommend.games" }]
requires-python = "==3.14.*"
dependencies = [
    "more-itertools",
    "pandas",
    "pytility",
    "tabulate",
]

[dependency-groups]
dev = [
    "jupyter-black",
    "jupyterlab",
    "jupytext",
    "mypy",
    "ruff",
    "types-tqdm",
]

[tool.ruff]
target-version = "py314"

[tool.mypy]
python_version = "3.14"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
