# All available Hugo versions are listed here: https://gitlab.com/pages/hugo/container_registry
image: hugomods/hugo:debian-reg-dart-sass-go-git-0.160.1

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - curl -LsSf https://astral.sh/uv/install.sh | sh
  - source $HOME/.local/bin/env

test:
  script:
  - uv run sync_assets.py
  - hugo
  artifacts:
    expire_in: 1 hour
  except:
  - master

pages:
  script:
  - uv run sync_assets.py
  - hugo
  artifacts:
    paths:
    - public
    expire_in: 48 hours
  only:
  - master
