image: hugomods/hugo:git-0.160.1

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - wget -qO- https://astral.sh/uv/install.sh | sh
  - source $HOME/.local/bin/env
  - hugo version

test:
  script:
    - uv run sync_assets.py
    - hugo --minify
  artifacts:
    expire_in: 1 hour
  except:
    - master

pages:
  script:
    - uv run sync_assets.py
    - hugo --minify
  artifacts:
    paths:
      - public
    expire_in: 48 hours
  only:
    - master
