baseurl: https://blog.recommend.games/

archetypeDir: archetypes
assetDir: assets
contentdir: content
dataDir: data
layoutdir: layouts
publishdir: public
staticDir: static
themesDir: themes

title: Recommend.Games Blog
canonifyurls: true

DefaultContentLanguage: en
theme: beautifulhugo
metaDataFormat: yaml
pygmentsUseClasses: true
pygmentCodeFences: true
disqusShortname: recommend-games
googleAnalytics: UA-128891980-1
enableRobotsTXT: true

Params:
  subtitle: Board Game Analyses
  mainSections:
    - post
    - posts
  logo: logo.png
  favicon: favicon.ico
  dateFormat: January 2, 2006
  commit: false
  rss: true
  comments: true
  # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"
  gcse: 013480686921635014344:zokjfkkzyza
  readingTime: true
  wordCount: true
  useHLJS: true
  socialShare: true
  showRelatedPosts: true

Author:
  name: Recommend.Games
  email: contact@recommend.games
  website: https://recommend.games/
  # facebook: markus.r.shepherd
  # googleplus: +username # or xxxxxxxxxxxxxxxxxxxxx
  gitlab: recommend.games
  github: recommend-games
  bitbucket: recommend-games
  twitter: recommend_games
  # reddit: MarkusShepherd
  # linkedin: markusschepke
  # xing: username
  # stackoverflow: users/2634131/markus-shepherd
  # snapchat: username
  # instagram: funny_monkey_42
  # youtube: user/MarkusSchepke # or channel/channelname
  # soundcloud: username
  # spotify: username
  # bandcamp: username
  # itchio: username
  # keybase: username
  # vk: mshepherd
  paypal: mschepke
  kaggle: mshepherd

menu:
  main:
    - name: Recommend.Games
      url: https://recommend.games/#/
      weight: 10

    - name: About
      url: page/about/
      weight: 20

    - name: Tags
      url: tags/
      weight: 30

sitemap:
  changefreq: weekly
