#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = [
#   "pyyaml",
# ]
# ///

import shutil
from pathlib import Path

import yaml

REPO = Path(__file__).parent
MAPPING = REPO / "asset-links.yaml"
GITIGNORE = REPO / "content/posts/.gitignore"


def needs_update(src: Path, dst: Path) -> bool:
    if not dst.exists():
        return True
    return src.stat().st_mtime > dst.stat().st_mtime


def main() -> None:
    data = yaml.safe_load(MAPPING.read_text())
    links = data.get("links", [])

    gitignore_lines = ["# Generated by sync_assets.py — do not edit manually"]

    for entry in links:
        src = REPO / entry["src"]
        dst = REPO / entry["dst"]
        rel = Path(entry["dst"]).relative_to("content/posts")
        gitignore_lines.append(f"/{rel}")

        if not src.exists():
            print(f"WARN: source missing: {src}")
            continue

        dst.parent.mkdir(parents=True, exist_ok=True)

        if dst.is_symlink():
            dst.unlink()

        if src.is_dir():
            if dst.exists():
                shutil.rmtree(dst)
            shutil.copytree(src, dst)
            print(f"  dir  {entry['src']} → {entry['dst']}")
        elif needs_update(src, dst):
            shutil.copy2(src, dst)
            print(f"  copy {entry['src']} → {entry['dst']}")

    GITIGNORE.write_text("\n".join(gitignore_lines) + "\n")
    print(f"Wrote {GITIGNORE}")


if __name__ == "__main__":
    main()
