[project]
name = "elo-experiments"
version = "0.1.0"
description = "Notebooks and assets for the Elo articles"
authors = [
    { name = "Markus Shepherd", email = "markus@recommend.games" },
]

requires-python = "==3.13.*"
dependencies = [
    "elo",
]

[dependency-groups]
dev = [
    "codetiming",
    "jupyter-black",
    "jupyterlab",
    "jupytext",
]

[tool.uv.sources]
elo = { git = "https://gitlab.com/recommend.games/elo.git", rev = "ac21f2907e919c8964b473fa4ee1de412119090e" }
